### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by cement-hools** [pixelbyaj/msgraph-email#4]
[

](https://github.com/pixelbyaj/msgraph-email/blame/46968608cba1e9ad46ba3b0092cfce5a1c3452c8/mail/msgraph/_email_service.py#L49-L51)

https://github.com/pixelbyaj/msgraph-email/blame/46968608cba1e9ad46ba3b0092cfce5a1c3452c8/mail/msgraph/_email_service.py#L55-L56

sentDateTime
https://github.com/pixelbyaj/msgraph-email/blame/46968608cba1e9ad46ba3b0092cfce5a1c3452c8/mail/msgraph/_email_service.py#L140

**Comment by pixelbyaj** [comment]
Thank you @cement-hools. The issue has been addressed and the new version **msgraph-email 1.1.2** has been released.
